Repository SSUMC-8th/Spring_Boot_D, pull requests merged in 2025-05, with the labels that each got.

#9 [Minne] Chapter 5. JPA 기초 및 프로젝트 구조
  src/main/java/umc/spring/domain/AgreedTerm.java
  src/main/java/umc/spring/domain/Food.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/MissionId.java
  src/main/java/umc/spring/domain/OpenHour.java
  src/main/java/umc/spring/domain/PreferredFood.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Restaurant.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/ReviewId.java
  src/main/java/umc/spring/domain/ReviewPhoto.java
  src/main/java/umc/spring/domain/Term.java
  src/main/java/umc/spring/domain/TryMission.java
  src/main/java/umc/spring/domain/TryMissionId.java
  src/main/java/umc/spring/domain/enums/Gender.java
  src/main/java/umc/spring/domain/enums/MemeberStatus.java
  src/main/java/umc/spring/domain/enums/SocialType.java
  src/main/resources/application.yml
Labels: ✨ Chapter05

#22 [에몽] Chapter 6. JPA 활용
  .gitignore
  build.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/FoodCategory.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#18 [오비] Chapter 6. JPA 활용
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/spring.main.iml
  .idea/vcs.xml
  build.gradle
  build/classes/java/main/umc/spring/Application.class
  build/classes/java/main/umc/spring/domain/Restaurant.class
  build/reports/problems/problems-report.html
  build/tmp/compileJava/compileTransaction/stash-dir/Coffee.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/CoffeeRepository.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Restaurant.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#20 [민니] Chapter 6. JPA 활용
  .gitignore
  build.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Restaurant.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  src/main/java/umc/spring/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryService.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantQueryServiceImpl.java
Labels: ✨ Chapter06

#29 [오비] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  build/reports/problems/problems-report.html
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#25 [민니] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#27 [므느] Chapter 7. API 응답 통일 & 에러 핸들러
  spring/build.gradle
  spring/src/main/java/umc/spring/StudyApplication.java
  spring/src/main/java/umc/spring/apiPayload/ApiResponse.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseErrorResponse.java
  spring/src/main/java/umc/spring/apiPayload/code/BaseResponse.java
  spring/src/main/java/umc/spring/apiPayload/code/ErrorResponseDto.java
  spring/src/main/java/umc/spring/apiPayload/code/ResponseDto.java
  spring/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  spring/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  spring/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  spring/src/main/java/umc/spring/apiPayload/status/ErrorResponse.java
  spring/src/main/java/umc/spring/apiPayload/status/SuccessResponse.java
  spring/src/main/java/umc/spring/converter/TempConverter.java
  spring/src/main/java/umc/spring/repository/storerepository/StoreRepository.java
  spring/src/main/java/umc/spring/repository/storerepository/StoreRepositoryCustom.java
  spring/src/main/java/umc/spring/repository/storerepository/StoreRepositoryImpl.java
  spring/src/main/java/umc/spring/service/storeservice/StoreQueryService.java
  spring/src/main/java/umc/spring/service/storeservice/StoreQueryServiceImpl.java
  spring/src/main/java/umc/spring/service/tempservice/TempQueryService.java
  spring/src/main/java/umc/spring/service/tempservice/TempQueryServiceImpl.java
  spring/src/main/java/umc/spring/web/controller/TempRestController.java
  spring/src/main/java/umc/spring/web/dto/TempRequest.java
  spring/src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#24 [에몽] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#39 [민니] Chapter 8. API & Swagger & Annotation
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/RestaurantConverter.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/MissionId.java
  src/main/java/umc/spring/repository/RegionRepository.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantCommandService.java
  src/main/java/umc/spring/service/RestaurantService/RestaurantCommandServiceImpl.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/RestaurantRestController.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/RestaurantRequestDTO.java
Labels: ✨ Chapter08
